language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - DEPENDENCIES=""
    - php: 7.4
      env:
        - DEPENDENCIES=""
    - php: 8.0
      env:
        - DEPENDENCIES=""
    - php: 8.0
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

